### ISSUE TITLE
I encountered an error when I replaced item_details

### ISSUE THREAD

**Issue by amanu-nur** [agung96tm/adonis-midtrans#1]
Error Response 
`E_INVALID_TRANSACTION: undefined > More details: https://err.sh/agung96tm/adonis-midtrans-helpers/E_INVALID_TRANSACTION`

I'm having an error changing item_details, for the price & quantity section

**Comment by agung96tm** [comment]
Ensure total of item_details (price * quantity) same as gross_amount. I think problem come from there.
Can you give me an example how do you send your transaction data ?

(* btw: i updated adonis-midtrans

**Comment by amanu-nur** [comment]
`class ExampleController {
  async charge() {
    let transaction_data = {
      transaction_details: {
        order_id: Math.floor(Date.now() / 1000),
        gross_amount: 30000
      },
      customer_details: {
        first_name: 'Mr. Awesome',
        email: 'mr_awesome@example.com'
      },
      customer_expiry: {
        start_time: moment().format('Y-MM-DD HH:mm:ss Z'),
        unit: 'day',
        duration: 2
      },
      item_details: [
        {
          id: 'PROD-1',
          quantity: 1,
          name: 'Product-1',
          price: 10000
        },
        {
          id: 'PROD-2',
          quantity: 1,
          name: 'Product-2',
          price: 20000
        }
      ],
      credit_card_option: {
        secure: true,
        channel: 'migs'
      }
    }`

I just used the sample you provided, then I replaced it directly in `item_details`. The price and quantity of the goods will indicate an error. if i don't replace it will be normal as usual

**Comment by amanu-nur** [comment]
> Ensure total of item_details (price * quantity) same as gross_amount. I think problem come from there.
> Can you give me an example how do you send your transaction data ?
> 
> (* btw: i updated adonis-midtrans

Okay, thanks

**Comment by amanu-nur** [comment]
> Ensure total of item_details (price * quantity) same as gross_amount. I think problem come from there.
> Can you give me an example how do you send your transaction data ?
> 
> (* btw: i updated adonis-midtrans

oh well it turns out I was careless when entering data, sorry

**Comment by agung96tm** [comment]
No problem dude, 
your issue make me understand, how important error exception and update documentation 😁
